spring:
  application:
    name: wheather-app
  mail:
    host: smtp.gmail.com
    port: 587
    username: sureshkukkala5544@gmail.com
    password: eqnw yrzr ugpx kltj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

openweather:
  api:
    key: OPENWEATHER_API_KEY
    url: https://api.openweathermap.org/data/2.5/weather